name: richhf
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - cudatoolkit=11.8
  - pytorch=2.0.0
  - torchvision=0.15.1
  - pip:
      - transformers==4.32.0
      - datasets==2.16.1
      - scipy==1.11.4
      - tensorboard==2.18.0
      - scikit-learn==1.3.2